
select * from spells;
        INSERT INTO spells (`spell_name`, `damage`, `effect`, `rank`)
        VALUES
    ("Smashing spell of Fire", 450, "Fire Burn", 450)
,("Smashing spell of Tremendous Gas", 300, "Smell Bad", 300)
,("Smashing spell of Damage", 450, "Double Damage", 450)
,("Smashing spell of Regeneration", -135, "Regeneration", 135)
,("Unweildable spell of Tremendous Gas", 180, "Smell Bad", 180)
,("Ragged spell of Tremendous Gas", 60, "Smell Bad", 60)
,("Heavy spell of Lightning", 60, "Paralyze", 60)
,("Unweildable spell of Water", 240, "Drown", 240)
,("Heavy spell of Regeneration", -48, "Regeneration", 48)
,("Smashing spell of Ice", 420, "Ice Burn", 420)
,("Unusual spell of Damage", 225, "Double Damage", 225)
,("Unweildable spell of Lightning", 60, "Paralyze", 60)
,("Ragged spell of Lightning", 75, "Paralyze", 75)
,("Crushing spell of Healing", -270, "Heal", 270)
,("Unbreakable spell of Healing", -750, "Heal", 750)
,("Smashing spell of Lightning", 150, "Paralyze", 150)
,("Unbreakable spell of Lightning", 50, "Paralyze", 50)
,("Heavy spell of Tremendous Gas", 80, "Smell Bad", 80)
,("Flying spell of Fire", 150, "Fire Burn", 150)
,("Ragged spell of Ice", 84, "Ice Burn", 84)
,("Flying spell of Water", 150, "Drown", 150)
,("Flying spell of Regeneration", -225, "Regeneration", 225)
,("Crushing spell of Regeneration", -216, "Regeneration", 216)
,("Unweildable spell of Ice", 336, "Ice Burn", 336)
,("Heavy spell of Damage", 180, "Double Damage", 180)
,("Crushing spell of Lightning", 90, "Paralyze", 90)
,("Unusual spell of Fire", 50, "Fire Burn", 50)
,("Unusual spell of Water", 25, "Drown", 25)
,("Unusual spell of Tremendous Gas", 25, "Smell Bad", 25)
,("Flying spell of Lightning", 150, "Paralyze", 150)
,("Crushing spell of Fire", 360, "Fire Burn", 360)
,("Smashing spell of Water", 300, "Drown", 300)
,("Unbreakable spell of Fire", 400, "Fire Burn", 400)
,("Unusual spell of Ice", 140, "Ice Burn", 140)
,("Crushing spell of Damage", 270, "Double Damage", 270)
,("Heavy spell of Healing", -180, "Heal", 180)
,("Unweildable spell of Regeneration", -72, "Regeneration", 72)
,("Heavy spell of Fire", 120, "Fire Burn", 120)
,("Ragged spell of Healing", -180, "Heal", 180)
,("Unbreakable spell of Water", 50, "Drown", 50)
,("Flying spell of Ice", 105, "Ice Burn", 105)
,("Unweildable spell of Healing", -720, "Heal", 720)
,("Unusual spell of Regeneration", -30, "Regeneration", 30)
,("Flying spell of Damage", 1125, "Double Damage", 1125)
,("Unweildable spell of Fire", 120, "Fire Burn", 120)
,("Unbreakable spell of Regeneration", -90, "Regeneration", 90)
,("Ragged spell of Damage", 225, "Double Damage", 225)
,("Heavy spell of Ice", 28, "Ice Burn", 28)
,("Unbreakable spell of Ice", 140, "Ice Burn", 140)
,("Unusual spell of Healing", -75, "Heal", 75)
,("Unusual spell of Lightning", 125, "Paralyze", 125)
,("Unweildable spell of Damage", 360, "Double Damage", 360)
,("Crushing spell of Tremendous Gas", 270, "Smell Bad", 270);
