INSERT INTO quest (`min_lvl`, `quest_text`, `quest_name`)
    VALUES
    (2, "Deep below the earth, the local Mages discover a horrible truth: Nagash is being raised! Using magical scrying techniques spy on the undead world, they discovers that this is a lengthy process, masterminded by a wizened necromancer, Gartax. Older than the hills and twice as tough, Gartax has been working night and day to bring Nagash back to life. If the warriors kill him, it may not stop Nagash being raised, but it will be a crippling blow to the process. The quest takes place within the Dark Crypts, where Nagash was buried. The warriors must make their way through the dark crypts to the throne room of Nagash, where Gartax is conducting the necromantic ceremony.", "Assassins"),
    (3, "The Warriors have found a city deep underground, swarming with monsters. The complex is gigantic, and actually has shops and homes, including a king in the Objective Room.", "Underworld City"),
    (4, "One of the Warriors was attacked by a werewolf and torn horribly on a trip to a Settlement, and upon arrival discovered he was infected by the Curse of the Wolf. Hurled from the City, the Warrior sought an answer for the cure to this curse, and with his friends learned of the Fountain of Light buried deep in the mountains. Supposedly enchanted with great power, this Fount is able to heal any affliction, remove any curse, for a price. With little else to try, the Warriors set out for the Fountain of Light, racing against the full moon.", "Curse of the Wolf "),
    (5, "Deep under the World’s Edge Mountains was a Dwarven stronghold of great wealth and reknown. Most of the world knew of Karak Khazad, and its fabulous metal works, producing items of power and beauty. But with the fall of the Dwarves, the forge at Karak Khazad was lost, and its enchanted anvil abandoned. Now the foul creatures living in the ruins use the anvil for their own purposes, and although unable to attain its full potential, the results are truly troubling nonetheless. The Dwarven Enchanter Smith Dol Gondur has hired the Warriors to retrieve this anvil, and return it to him. In payment, he will either offer D6x200 gold or an item he creates with the anvil. If the item is chosen, make two rolls on the Weapons and Armor Dungeon Room Treasure table, and choose the one the Warriors like the best. This he gives to them for free.", "The Forge of Karak Khazad"),
    (6, "A foolish group of young men from the nearby village has taken a dare and gone into the local dungeon, never to return. Their families plead the Warriors to at least find out what became of the idiots, all 6 of them, and will pay 20 gold and 2D6 provisions for each one that they bring home alive. Doubtful, but interested in finding out, the Warriors enter the dungeon. ", "Rescue"),
    (7, " In the local area, there is a spring of water said so pure and clear that it is able to remove the taint of any curse or poison by washing in it. The Warriors are hired to take a cursed item from the local lord, a signet ring, and cleanse it of the dark curse that lies upon it by using the spring. The Lord is confident that they Warriors can reach it, and at the very least, they should make it far enough in the ring won’t be found any time soon to extend its curse on the Lord’s family any longer. Should the Warriors return with the signet ring, the Lord gives them D6x25 gold each and presents them with a cart.", "Purifying Spring"),
    (8, "Skaven under the last settlement the Warriors visited have found the spring that feeds the towns main water supply. Snickering evilly, they placed a sliver of warpstone into the spring, thus contaminating the water of the settlement. The people of the settlement beg the Warriors to enter the catacombs beneath the settlement and assist them, offering rewards and laud if they can save the water from this poison. Should the Warriors succeed, they are given a total of gold equal to 50 x (2D6 for a village, 4D6 for a town, and 6D6 for a city).", "The Poisoned Water Supply"),
    (9, "Hidden in the forest nearby is a shrine of Knowledge, able to grant wisdom to one who reads its runic base and meditates. The Warriors are in the area and decide to give it a try, although the locals warn it is not a safe place to travel.", "The Shrine of Knowlege"),
    (10, "An outpost of Dark Elves nearby has been wreaking havoc in the nearby settlements, raids and slave capturing parties have spread their evil among the Empire, and worse yet, the Witch Elves are strong there. An army of the Dark Elves led by these horrible women using their Blood Cauldron has caused great destruction near the outpost. The local mages believe there is a Font of Blood in the outpost, an abhorrent spring of blood that the Witch Elves use to fill their cauldron and bathe in, rejuvenating them and fuelling their dark magic. .. The Warriors have been hired to destroy this Font, using a special Dwarven bomb while the Dark Elf army is away raiding a town. The Empire will assault the outpost, and mourn the town’s loss later, giving you what they expect only minimal resistance as you make your way to the Font and demolish it. When the Warriors destroy the Font and return, they will be given D6x100 gold each and a treasure card each.", "Font of Blood");

SELECT * FROM quest;